export type PageSource = 'foundation' | 'primitives' | 'fluent-web' | 'teams';

export type PageMeta = {
  key: string;
  label: string;
  description: string;
  source: PageSource;
  emphasis: string;
};

export const pages = [
  {
    key: 'analytics-overview',
    label: '分析总览',
    description: '验证数据总览、趋势图和摘要侧栏在 Fluent 2 下的节奏。',
    source: 'foundation',
    emphasis: '总览',
  },
  {
    key: 'app-shell',
    label: '应用壳 + 仪表盘',
    description: '验证 Fluent 2 企业后台的导航、摘要卡、顶部命令区和主工作区层级。',
    source: 'foundation',
    emphasis: '应用壳',
  },
  {
    key: 'project-board',
    label: '项目看板',
    description: '验证卡片看板、列结构和任务优先级表达。',
    source: 'foundation',
    emphasis: '看板',
  },
  {
    key: 'settings-center',
    label: '设置中心',
    description: '验证设置页分组、说明、开关和保存动作的组合方式。',
    source: 'foundation',
    emphasis: '设置',
  },
  {
    key: 'people-directory',
    label: '成员目录',
    description: '验证卡片式人员目录和轻量成员信息布局。',
    source: 'foundation',
    emphasis: '目录',
  },
  {
    key: 'calendar-planner',
    label: '日程规划',
    description: '验证日历块状布局和多列响应式折叠方式。',
    source: 'foundation',
    emphasis: '日历',
  },
  {
    key: 'resource-library',
    label: '资源库',
    description: '验证资源卡片、预览块和搜索条组合。',
    source: 'foundation',
    emphasis: '资源',
  },
  {
    key: 'notification-preferences',
    label: '通知偏好',
    description: '验证偏好设置页里开关、说明和底部动作的节奏。',
    source: 'foundation',
    emphasis: '偏好',
  },
  {
    key: 'audit-timeline',
    label: '审计时间线',
    description: '验证时间线、状态标签和审计型页面层级。',
    source: 'foundation',
    emphasis: '时间线',
  },
  {
    key: 'message-center',
    label: '消息中心',
    description: '验证活动流、筛选区、消息密度与状态反馈在 Fluent 2 下的组合方式。',
    source: 'foundation',
    emphasis: '消息流',
  },
  {
    key: 'login-showcase',
    label: '登录页',
    description: '验证 Fluent 2 企业产品常见的双栏登录结构和聚焦式表单布局。',
    source: 'foundation',
    emphasis: '登录',
  },
  {
    key: 'grid-drawer',
    label: '列表 + 抽屉',
    description: '适合治理页、资源列表和右侧详情编辑场景。',
    source: 'foundation',
    emphasis: '列表',
  },
  {
    key: 'tree-detail',
    label: '树 + 详情',
    description: '适合菜单树、资源树、分类树和结构管理场景。',
    source: 'foundation',
    emphasis: '树形',
  },
  {
    key: 'form-sections',
    label: '分组表单',
    description: '适合设置页、详情编辑页和抽屉配置表单。',
    source: 'foundation',
    emphasis: '表单',
  },
  {
    key: 'operations-command',
    label: '运营指挥台',
    description: '验证跨区域运营调度、事件队列和责任人上下文如何共存于一张稳定工作台。',
    source: 'foundation',
    emphasis: '运营调度',
  },
  {
    key: 'tenant-overview',
    label: '租户总览',
    description: '验证多租户后台下的概览、容量状态与租户治理入口的层级。',
    source: 'foundation',
    emphasis: '租户管理',
  },
  {
    key: 'billing-operations',
    label: '计费运营',
    description: '验证计费异常、账单检查和回收任务在 Fluent 2 下的运营工作面。',
    source: 'foundation',
    emphasis: '计费运营',
  },
  {
    key: 'incident-response',
    label: '事件响应台',
    description: '验证告警、恢复步骤、责任人和沟通摘要在事件响应页中的层级。',
    source: 'foundation',
    emphasis: '事件响应',
  },
  {
    key: 'policy-studio',
    label: '策略工作室',
    description: '验证策略编辑、影响面预览与发布治理在共享基座下的组合方式。',
    source: 'foundation',
    emphasis: '策略治理',
  },
  {
    key: 'asset-inventory',
    label: '资产台账',
    description: '验证资产检索、状态明细与生命周期动作在企业风格下的表达。',
    source: 'foundation',
    emphasis: '台账管理',
  },
  {
    key: 'support-desk',
    label: '客服支持台',
    description: '验证支持队列、工单摘要和升级动作在共享基座工作台里的组织方式。',
    source: 'foundation',
    emphasis: '客服支持',
  },
  {
    key: 'search-workspace',
    label: '全局检索台',
    description: '验证全局搜索、结果分组与右侧上下文在高密度页中的关系。',
    source: 'foundation',
    emphasis: '全局检索',
  },
  {
    key: 'release-control',
    label: '发布控制台',
    description: '验证发布批次、风险检查与回滚信息在一张控制面里的节奏。',
    source: 'foundation',
    emphasis: '发布治理',
  },
  {
    key: 'knowledge-hub',
    label: '知识中枢',
    description: '验证知识检索、精选内容和操作指引在低噪文档页中的平衡。',
    source: 'foundation',
    emphasis: '知识中枢',
  },
  {
    key: 'fluent-gallery',
    label: 'Fluent 组件展示',
    description: '偏 Microsoft Fluent 2 Web 的组件、状态与说明型页面测试样式。',
    source: 'primitives',
    emphasis: '组件',
  },
  {
    key: 'react-actions-navigation',
    label: 'React 组件页：命令与导航',
    description: '按 Fluent 2 官方 React 组件目录集中展示按钮、导航、命令条和结构切换组件。',
    source: 'primitives',
    emphasis: '命令与导航',
  },
  {
    key: 'react-forms-selection',
    label: 'React 组件页：表单与选择',
    description: '集中展示字段、输入、选择、布尔控制和范围输入组件。',
    source: 'primitives',
    emphasis: '表单与选择',
  },
  {
    key: 'react-feedback-overlays',
    label: 'React 组件页：反馈与浮层',
    description: '集中展示反馈、进度、加载、抽屉、对话框和提示类组件。',
    source: 'primitives',
    emphasis: '反馈与浮层',
  },
  {
    key: 'react-identity-content',
    label: 'React 组件页：身份与内容',
    description: '集中展示身份、内容容器、图像和基础内容排版组件。',
    source: 'primitives',
    emphasis: '身份与内容',
  },
  {
    key: 'react-icon-library',
    label: 'React 图标总览',
    description: '集中展示 @fluentui/react-icons 的基础图标 ID，并支持点击复制图标标识。',
    source: 'primitives',
    emphasis: '图标',
  },
  {
    key: 'react-composition-navigation-command',
    label: 'React 组合页：导航与命令',
    description: '把导航、检索、命令条和视图切换组合成真实的 Fluent 2 React 导航工作面。',
    source: 'primitives',
    emphasis: '导航组合',
  },
  {
    key: 'react-composition-form-feedback',
    label: 'React 组合页：表单与反馈',
    description: '把字段、选择、提交和反馈收口成真实的 Fluent 2 React 表单工作台。',
    source: 'primitives',
    emphasis: '表单组合',
  },
  {
    key: 'react-composition-content-collaboration',
    label: 'React 组合页：内容与协作',
    description: '把内容容器、责任人和协作提醒组合成真实的 Fluent 2 React 内容协作面。',
    source: 'primitives',
    emphasis: '内容组合',
  },
  {
    key: 'fluent-spec',
    label: 'Fluent 规范工作区',
    description: '偏 Microsoft Fluent 2 Web 的文档式工作区和组件规范页测试样式。',
    source: 'fluent-web',
    emphasis: '规范',
  },
  {
    key: 'approval-workbench',
    label: '审批工作台',
    description: '偏 Fluent 2 Web 的治理/审批页面测试样式，验证筛选区、队列和右侧详情区。',
    source: 'fluent-web',
    emphasis: '治理',
  },
  {
    key: 'shell-guidelines',
    label: '应用壳规范页',
    description: '偏 Fluent 2 Web 的文档式页面，验证应用壳说明、预览框和变体区。',
    source: 'fluent-web',
    emphasis: '应用壳规范',
  },
  {
    key: 'data-grid-spec',
    label: '数据网格规范',
    description: '验证数据网格文档页中的说明区、示例区和变体区如何收口。',
    source: 'fluent-web',
    emphasis: 'DataGrid 规范',
  },
  {
    key: 'form-patterns',
    label: '表单模式库',
    description: '验证 Fluent 2 Web 文档页里表单模式、示例和状态说明的关系。',
    source: 'fluent-web',
    emphasis: '表单模式',
  },
  {
    key: 'navigation-spec',
    label: '导航结构规范',
    description: '验证 Fluent 2 Web 导航类文档页的目录、正文和预览区层级。',
    source: 'fluent-web',
    emphasis: '导航结构',
  },
  {
    key: 'token-governance',
    label: 'Token 治理台',
    description: '验证 Token 规范、变量说明和治理入口在文档式工作区中的表达。',
    source: 'fluent-web',
    emphasis: '设计 Token',
  },
  {
    key: 'accessibility-review',
    label: '可访问性评审',
    description: '验证 Fluent 2 可访问性评审页的检查项、说明区和示例布局。',
    source: 'fluent-web',
    emphasis: '可访问性',
  },
  {
    key: 'handoff-patterns',
    label: 'Handoff 模式页',
    description: '验证设计交付和开发 handoff 场景在 Fluent 2 Web 下的文档语法。',
    source: 'fluent-web',
    emphasis: 'Handoff',
  },
  {
    key: 'template-gallery',
    label: '模板画廊',
    description: '验证模板目录、预览区和调用动作在 Fluent 2 Web 下的页面组合。',
    source: 'fluent-web',
    emphasis: '模板目录',
  },
  {
    key: 'motion-principles',
    label: '动效原则页',
    description: '验证动效说明、状态变体和预览区域在文档式页面中的平衡。',
    source: 'fluent-web',
    emphasis: '动效原则',
  },
  {
    key: 'sidepanel-reference',
    label: '侧板参考页',
    description: '验证侧板、抽屉和辅助信息区在 Fluent 2 Web 里的规范表达。',
    source: 'fluent-web',
    emphasis: '侧板参考',
  },
  {
    key: 'teams-responsive',
    label: 'Teams 响应式',
    description: '基于 Microsoft Teams UI Kit 的响应式设计页测试稿，验证三栏信息架构与设备预览表达。',
    source: 'teams',
    emphasis: '响应式',
  },
  {
    key: 'teams-channel',
    label: 'Teams 频道工作台',
    description: '验证 Teams 风格频道、活动流、任务区和右侧成员栏如何收口成协作型后台页面。',
    source: 'teams',
    emphasis: '频道',
  },
  {
    key: 'teams-conversation',
    label: 'Teams 消息线程',
    description: '验证 Teams 风格线程列表、主讨论区和右侧信息栏如何转成协作沟通页。',
    source: 'teams',
    emphasis: '消息',
  },
  {
    key: 'meeting-command',
    label: '会议指挥页',
    description: '验证会议准备、会中指挥和右侧参会角色在 Teams 风格下的页面组合。',
    source: 'teams',
    emphasis: '会议协同',
  },
  {
    key: 'frontline-briefing',
    label: '一线简报台',
    description: '验证一线简报、待升级事项和轮班角色在 Teams 协作布局中的节奏。',
    source: 'teams',
    emphasis: '一线简报',
  },
  {
    key: 'file-collaboration',
    label: '文件协作台',
    description: '验证文件讨论、审阅流和共享资料侧栏在 Teams 风格下的页面组合。',
    source: 'teams',
    emphasis: '文件协作',
  },
  {
    key: 'approval-conversation',
    label: '审批会话页',
    description: '验证审批线程、上下文说明和责任人评论在 Teams 语法下的收口。',
    source: 'teams',
    emphasis: '审批会话',
  },
  {
    key: 'onboarding-hub',
    label: '入职协作台',
    description: '验证入职任务、欢迎流和责任人协作在 Teams 风格页面中的表达。',
    source: 'teams',
    emphasis: '入职协同',
  },
  {
    key: 'community-announcements',
    label: '社区公告台',
    description: '验证社区公告、讨论回应和运营节奏在 Teams 风格下的页面组织。',
    source: 'teams',
    emphasis: '公告与回应',
  },
  {
    key: 'shift-handoff',
    label: '交接班中心',
    description: '验证交接记录、值守任务和待升级事项在 Teams 协作布局中的节奏。',
    source: 'teams',
    emphasis: '交接班',
  },
  {
    key: 'webinar-operations',
    label: '活动运营频道',
    description: '验证线上活动准备、素材协调和直播值守在 Teams 风格下的工作面。',
    source: 'teams',
    emphasis: '活动运营',
  },
  {
    key: 'incident-swarm',
    label: '事件协同频道',
    description: '验证事件协同、跨团队评论和升级广播在 Teams 风格下的页面表达。',
    source: 'teams',
    emphasis: '事件协同',
  },
  {
    key: 'partner-standup',
    label: '伙伴站会台',
    description: '验证伙伴协作、行动项和共享问题清单在 Teams 风格下的日常工作面。',
    source: 'teams',
    emphasis: '伙伴协作',
  },
] as const satisfies readonly PageMeta[];

export type PageKey = (typeof pages)[number]['key'];
