import type { FluentScenarioConfig, FoundationScenarioConfig, TeamsScenarioConfig } from './scenario-templates';

type Tone = 'brand' | 'success' | 'warning';
type BadgeTuple = [label: string, color?: Tone, appearance?: 'filled' | 'tint' | 'outline'];

function buildFoundationScenario(input: {
  eyebrow: string;
  title: string;
  description: string;
  emphasis: string;
  railTitle: string;
  railDescription: string;
  railItems: Array<[string, string, boolean?]>;
  badges: BadgeTuple[];
  heroTitle: string;
  heroBody: string;
  heroSupport: string;
  stats: Array<[string, string, Tone?]>;
  primaryTitle: string;
  primaryAction: string;
  primaryItems: Array<[string, string, string, string?, Tone?]>;
  secondaryTitle: string;
  secondaryAction: string;
  secondaryItems: Array<[string, string, string, string?, Tone?]>;
  asideTitle: string;
  asideDescription: string;
  asideItems: Array<[string, string, string?, Tone?]>;
  notes: string[];
}): FoundationScenarioConfig {
  return {
    eyebrow: input.eyebrow,
    title: input.title,
    description: input.description,
    emphasis: input.emphasis,
    badges: input.badges.map(([label, color, appearance]) => ({ label, color, appearance })),
    railTitle: input.railTitle,
    railDescription: input.railDescription,
    railItems: input.railItems.map(([title, subtitle, active]) => ({ title, subtitle, active })),
    heroTitle: input.heroTitle,
    heroBody: input.heroBody,
    heroSupport: input.heroSupport,
    stats: input.stats.map(([label, value, tone]) => ({ label, value, tone })),
    primaryTitle: input.primaryTitle,
    primaryAction: input.primaryAction,
    primaryItems: input.primaryItems.map(([title, description, meta, badgeText, badgeTone]) => ({
      title,
      description,
      meta,
      badgeText,
      badgeTone,
    })),
    secondaryTitle: input.secondaryTitle,
    secondaryAction: input.secondaryAction,
    secondaryItems: input.secondaryItems.map(([title, description, meta, badgeText, badgeTone]) => ({
      title,
      description,
      meta,
      badgeText,
      badgeTone,
    })),
    asideTitle: input.asideTitle,
    asideDescription: input.asideDescription,
    asideItems: input.asideItems.map(([title, subtitle, badgeText, badgeTone]) => ({
      title,
      subtitle,
      badgeText,
      badgeTone,
    })),
    notes: input.notes,
  };
}

function buildFluentScenario(input: {
  eyebrow: string;
  title: string;
  description: string;
  emphasis: string;
  badges: BadgeTuple[];
  stats: Array<[string, string, Tone?]>;
  navTitle: string;
  navItems: Array<[string, string]>;
  docTitle: string;
  docBody: string;
  docLinks: string[];
  docNotes: string[];
  variantTitle: string;
  variantAction: string;
  variants: Array<[string, string, string, boolean?]>;
  specimens: Array<[string, string, string[]]>;
}): FluentScenarioConfig {
  return {
    eyebrow: input.eyebrow,
    title: input.title,
    description: input.description,
    emphasis: input.emphasis,
    badges: input.badges.map(([label, color, appearance]) => ({ label, color, appearance })),
    stats: input.stats.map(([label, value, tone]) => ({ label, value, tone })),
    navTitle: input.navTitle,
    navItems: input.navItems.map(([title, subtitle]) => ({ title, subtitle })),
    docTitle: input.docTitle,
    docBody: input.docBody,
    docLinks: input.docLinks,
    docNotes: input.docNotes,
    variantTitle: input.variantTitle,
    variantAction: input.variantAction,
    variants: input.variants.map(([title, subtitle, buttonLabel, primary]) => ({
      title,
      subtitle,
      buttonLabel,
      primary,
    })),
    specimens: input.specimens.map(([title, description, lines]) => ({ title, description, lines })),
  };
}

function buildTeamsScenario(input: {
  eyebrow: string;
  title: string;
  description: string;
  emphasis: string;
  badges: BadgeTuple[];
  channelTitle: string;
  channelDescription: string;
  channelItems: Array<[string, string, boolean?]>;
  heroTitle: string;
  heroBody: string;
  heroSupport: string;
  stats: Array<[string, string, Tone?]>;
  feedTitle: string;
  feedAction: string;
  feedItems: Array<[string, string, string, string?, Tone?]>;
  taskTitle: string;
  taskAction: string;
  taskItems: Array<[string, string, string, string?, Tone?]>;
  membersTitle: string;
  membersDescription: string;
  memberItems: Array<[string, string, string?, Tone?]>;
  notes: string[];
}): TeamsScenarioConfig {
  return {
    eyebrow: input.eyebrow,
    title: input.title,
    description: input.description,
    emphasis: input.emphasis,
    badges: input.badges.map(([label, color, appearance]) => ({ label, color, appearance })),
    channelTitle: input.channelTitle,
    channelDescription: input.channelDescription,
    channelItems: input.channelItems.map(([title, subtitle, active]) => ({ title, subtitle, active })),
    heroTitle: input.heroTitle,
    heroBody: input.heroBody,
    heroSupport: input.heroSupport,
    stats: input.stats.map(([label, value, tone]) => ({ label, value, tone })),
    feedTitle: input.feedTitle,
    feedAction: input.feedAction,
    feedItems: input.feedItems.map(([title, description, meta, badgeText, badgeTone]) => ({
      title,
      description,
      meta,
      badgeText,
      badgeTone,
    })),
    taskTitle: input.taskTitle,
    taskAction: input.taskAction,
    taskItems: input.taskItems.map(([title, description, meta, badgeText, badgeTone]) => ({
      title,
      description,
      meta,
      badgeText,
      badgeTone,
    })),
    membersTitle: input.membersTitle,
    membersDescription: input.membersDescription,
    memberItems: input.memberItems.map(([title, subtitle, badgeText, badgeTone]) => ({
      title,
      subtitle,
      badgeText,
      badgeTone,
    })),
    notes: input.notes,
  };
}

export const foundationScenarioData = {
  'operations-command': buildFoundationScenario({
    eyebrow: 'Operations Command',
    title: '运营指挥台',
    description: '验证跨区域运营调度、事件队列和责任人上下文如何共存于一张稳定工作台。',
    emphasis: '高密度运营面',
    railTitle: '运营脉络',
    railDescription: '共享基座页，重点验证指挥台、队列和责任分派的关系。',
    railItems: [['总览', '指标与例外', true], ['值守', '人员与班次'], ['队列', '待处理动作'], ['简报', '每日回顾']],
    badges: [['Foundation', 'brand', 'filled'], ['运营调度'], ['需快决策', 'warning']],
    heroTitle: '把队列、告警和下一步动作压进一个不失控的首屏。',
    heroBody: '这类页不追求装饰，而是让负责人一进来就知道哪里堵塞、谁在跟进、哪个动作最先执行。',
    heroSupport: '适合运营中台、值班控制面和跨团队日常调度页。',
    stats: [['待分配队列', '18', 'brand'], ['今日闭环', '42', 'success'], ['升级告警', '3', 'warning']],
    primaryTitle: '今日推进',
    primaryAction: '查看全部',
    primaryItems: [
      ['北区补货节奏已重排', '系统已把短缺仓库提到优先队列，等待值守确认最终派单。', '供应链 · 8 分钟前', '高优先级', 'warning'],
      ['高频工单已自动归组', '重复工单按区域和影响范围重组，减少一线重复判断。', '客服运营 · 22 分钟前', '稳定', 'success'],
      ['异常支付流量待复核', '支付异常仍处于观察窗，建议财务和风控同步复核。', '财务联席 · 今天 09:20', '需关注', 'warning'],
    ],
    secondaryTitle: '风险与跟进',
    secondaryAction: '导出简报',
    secondaryItems: [
      ['高峰订单可能晚于 SLA', '东区 2 个站点的人力冗余不足，预计 30 分钟后触发超时阈值。', '配送履约 · SLA 预警', '红色风险', 'warning'],
      ['自动化规则需要校准', '两条优先级规则在同一批次内命中，需要策略团队决定保序方案。', '规则团队 · 待确认', '待确认', 'brand'],
    ],
    asideTitle: '重点角色',
    asideDescription: '右栏只保留责任主体和低频辅助信息，不重复主工作区。',
    asideItems: [['履约值守', '负责升级队列和人工介入', '在线', 'success'], ['运营分析', '负责简报和阈值解释', '待回应', 'warning'], ['平台策略', '负责规则冲突收敛', '同步中', 'brand']],
    notes: ['首屏必须先给出“现在该做什么”，不要把说明文案放在最强层级。', '右栏信息只承担辅助上下文，不重复队列明细。'],
  }),
  'tenant-overview': buildFoundationScenario({
    eyebrow: 'Tenant Overview',
    title: '租户总览',
    description: '验证多租户后台下的概览、容量状态与租户治理入口的层级。',
    emphasis: '租户管理视角',
    railTitle: '租户范围',
    railDescription: '更偏管理总览和体检页的节奏。',
    railItems: [['租户状态', '健康分与风险', true], ['容量', '资源与额度'], ['连接', '集成状态'], ['治理', '策略入口']],
    badges: [['Foundation', 'brand', 'filled'], ['租户治理'], ['企业后台']],
    heroTitle: '租户总览页应该先交代健康度、资源占用和需要立即干预的对象。',
    heroBody: '把多租户信息收成统一体检页，比把所有租户堆成卡片墙更适合企业级后台。',
    heroSupport: '适合平台运维、客户成功和环境治理团队。',
    stats: [['活跃租户', '126', 'brand'], ['健康稳定', '118', 'success'], ['需干预', '8', 'warning']],
    primaryTitle: '本周异常租户',
    primaryAction: '进入租户列表',
    primaryItems: [
      ['Contoso East 健康度下降', '最近 24 小时 API 错误率提升，建议优先检查身份代理和限流配置。', '平台团队 · 今天', '需干预', 'warning'],
      ['Northwind Sandbox 超出容量阈值', '对象存储增速异常，系统已建议扩容或归档。', '资源平台 · 1 小时前', '容量预警', 'brand'],
    ],
    secondaryTitle: '治理动作',
    secondaryAction: '查看策略',
    secondaryItems: [
      ['批量轮换过期密钥', '18 个租户在未来 7 天内会进入凭证轮换窗口。', '安全基线 · 即将开始', '计划中', 'brand'],
      ['恢复演练窗口已排定', '本周五执行季度恢复演练，需提前锁定受影响租户。', '可靠性团队 · 本周', '需关注', 'warning'],
    ],
    asideTitle: '运营摘要',
    asideDescription: '给平台负责人一个低噪的租户背景区。',
    asideItems: [['付费计划', '企业版占比 72%', '稳定', 'success'], ['新增试用', '本周新增 14 个租户', '增长中', 'brand'], ['风险行业', '金融与医疗优先关注', '重点', 'warning']],
    notes: ['多租户总览不应退化成单纯的数字面板，必须给出治理入口。', '优先用租户健康和资源趋势建立首屏主线。'],
  }),
  'billing-operations': buildFoundationScenario({
    eyebrow: 'Billing Operations',
    title: '计费运营',
    description: '验证计费异常、账单检查和回收任务在 Fluent 2 下的运营工作面。',
    emphasis: '计费和回收',
    railTitle: '账单流程',
    railDescription: '适合财务运营、回款团队和客户成功协同。',
    railItems: [['账单批次', '生成与核对', true], ['异常款项', '争议与冲正'], ['提醒', '催缴节奏'], ['审计', '账务记录']],
    badges: [['Foundation', 'brand', 'filled'], ['计费运营'], ['高一致性']],
    heroTitle: '把账单批次、争议款项和提醒动作收在一个稳定的计费工作台里。',
    heroBody: '这类页面要优先交代本批次是否正常、异常款项有多少、下一步是提醒还是人工介入。',
    heroSupport: '适合订阅计费、企业账期和应收协同后台。',
    stats: [['待核账单', '34', 'brand'], ['回款成功率', '94%', 'success'], ['争议中', '6', 'warning']],
    primaryTitle: '异常账单',
    primaryAction: '查看批次',
    primaryItems: [
      ['四月企业账期批次待复核', '部分租户折扣规则冲突，需要先确认套餐覆盖范围。', '账务核对 · 今天 08:40', '待确认', 'brand'],
      ['Northwind 发票号码跳号', '发票序列在一轮重试后跳过 2 个号段，需要审计留痕。', '发票服务 · 40 分钟前', '异常', 'warning'],
    ],
    secondaryTitle: '回收动作',
    secondaryAction: '导出名单',
    secondaryItems: [
      ['本周催缴名单已生成', '高风险客户按行业和应收账龄自动分组，便于分配到客户成功。', '回收团队 · 已生成', '可执行', 'success'],
      ['自动扣费窗口即将开始', '夜间自动扣费批次将在 2 小时后开启，需确认支付网关状态。', '支付运营 · 倒计时', '需关注', 'warning'],
    ],
    asideTitle: '账务上下文',
    asideDescription: '放低频说明和账期背景，而不是主工作区明细。',
    asideItems: [['账期模型', '月结 + 季结并存', '稳定', 'success'], ['冲正窗口', '每日 18:00 截止', '规则', 'brand'], ['争议阈值', '超过 5% 触发人工介入', '重点', 'warning']],
    notes: ['计费页面要把批次和异常作为主线，不要让普通收入数字压过风险。', '应收和争议建议分成不同工作面，但在同页保持上下文联动。'],
  }),
  'incident-response': buildFoundationScenario({
    eyebrow: 'Incident Response',
    title: '事件响应台',
    description: '验证告警、恢复步骤、责任人和沟通摘要在事件响应页中的层级。',
    emphasis: '告警与恢复',
    railTitle: '事件通道',
    railDescription: '偏实时响应和跨职能协同的布局语法。',
    railItems: [['告警总线', '触发与升级', true], ['恢复步骤', '手册与执行'], ['沟通', '内外部同步'], ['复盘', '后续动作']],
    badges: [['Foundation', 'brand', 'filled'], ['事件响应'], ['高压场景', 'warning']],
    heroTitle: '响应页的主任务不是展示漂亮数据，而是让值守人员快速看见升级路径。',
    heroBody: '把恢复动作、责任人和对外同步节奏放在一页，比把它们分散到多个子页更适合一期实验场。',
    heroSupport: '适合故障值守、SRE 事件协调和安全响应页。',
    stats: [['开放事件', '4', 'warning'], ['恢复中', '2', 'brand'], ['平均响应', '7 分钟', 'success']],
    primaryTitle: '当前事件',
    primaryAction: '进入运行手册',
    primaryItems: [
      ['身份服务延迟飙升', '已锁定上游缓存抖动，正在执行降级策略并观察错误率回落。', 'SRE 值守 · 刚刚', '处理中', 'brand'],
      ['北区队列消费积压', '消息堆积来自依赖重试回路，需要暂停二次回放避免放大故障。', '平台服务 · 12 分钟前', '高风险', 'warning'],
    ],
    secondaryTitle: '恢复与同步',
    secondaryAction: '查看复盘草稿',
    secondaryItems: [
      ['外部状态页待更新', '当前可先同步受影响范围和已采取动作，再补预计恢复时间。', '客户沟通 · 立即执行', '需发布', 'brand'],
      ['复盘动作已生成草稿', '系统已根据事件时间线生成复盘条目，待责任人补全根因。', '质量团队 · 自动生成', '可用', 'success'],
    ],
    asideTitle: '值守上下文',
    asideDescription: '右栏保持人和规则，不和主响应面竞争。',
    asideItems: [['主值守', '负责恢复步骤与升级', '在线', 'success'], ['沟通负责人', '负责客户与销售同步', '待同步', 'warning'], ['观察窗口', '恢复后需保留 30 分钟', '规则', 'brand']],
    notes: ['事件页必须强调下一步动作，不要让指标卡片占据最强视觉。', '风险和恢复应保持近距离，不要割裂成两块无联系的区域。'],
  }),
  'policy-studio': buildFoundationScenario({
    eyebrow: 'Policy Studio',
    title: '策略工作室',
    description: '验证策略编辑、影响面预览与发布治理在共享基座下的组合方式。',
    emphasis: '策略编辑和影响面',
    railTitle: '策略层级',
    railDescription: '更偏配置治理和决策支持的工作台页。',
    railItems: [['策略目录', '规则与模板', true], ['影响面', '命中对象'], ['审阅', '审批与备注'], ['发布', '灰度与回滚']],
    badges: [['Foundation', 'brand', 'filled'], ['策略治理'], ['配置工作台']],
    heroTitle: '策略页面要同时看得见“规则内容”和“谁会被它影响”。',
    heroBody: '相比一味堆表单，更重要的是把影响面、审批和回滚信息放到同一层级中。',
    heroSupport: '适合权限策略、风控规则和自动化流程配置页。',
    stats: [['生效策略', '58', 'brand'], ['待审批', '9', 'warning'], ['命中率', '87%', 'success']],
    primaryTitle: '策略变更',
    primaryAction: '打开编辑器',
    primaryItems: [
      ['高风险审批规则待复核', '新版规则提升了拦截阈值，但仍需要业务负责人确认例外名单。', '策略团队 · 今天', '待审批', 'warning'],
      ['灰度发布窗口已开启', '系统已按租户规模拆分批次，可先发布到低风险租户。', '平台策略 · 刚刚', '可发布', 'success'],
    ],
    secondaryTitle: '影响面',
    secondaryAction: '导出命中对象',
    secondaryItems: [
      ['命中租户 126 个', '预计 38 个高频租户会在首日收到明显变化，建议同步客服脚本。', '影响评估 · 自动生成', '需沟通', 'brand'],
      ['回滚点已记录', '系统保留上个稳定版本，可在 5 分钟内恢复。', '发布安全 · 已准备', '可回滚', 'success'],
    ],
    asideTitle: '发布规则',
    asideDescription: '右栏放审批人、窗口和回滚信息。',
    asideItems: [['审批人', '安全负责人 + 业务 owner', '双签', 'brand'], ['发布窗口', '工作日 14:00 - 18:00', '规则', 'success'], ['回滚 SLA', '5 分钟内恢复上一版本', '保障', 'warning']],
    notes: ['策略页必须让用户看见影响面，而不是只有一整列字段。', '审批和回滚应作为一级上下文出现。'],
  }),
  'asset-inventory': buildFoundationScenario({
    eyebrow: 'Asset Inventory',
    title: '资产台账',
    description: '验证资产检索、状态明细与生命周期动作在企业风格下的表达。',
    emphasis: '目录 + 生命周期',
    railTitle: '资产域',
    railDescription: '偏清点、盘点和追踪的后台列表工作面。',
    railItems: [['全部资产', '按域聚合', true], ['盘点', '待核验清单'], ['维护', '维保与风险'], ['归档', '退场对象']],
    badges: [['Foundation', 'brand', 'filled'], ['台账管理'], ['目录型页面']],
    heroTitle: '资产页更适合“目录 + 生命周期动作”，而不是做成单纯图库。',
    heroBody: '把盘点、维保和风险并排展示，能让操作人员更快判断是查看详情还是发起维护。',
    heroSupport: '适合设备资产、软件授权和环境资源台账页。',
    stats: [['登记资产', '4,820', 'brand'], ['本周盘点', '312', 'success'], ['维保预警', '27', 'warning']],
    primaryTitle: '待处理资产',
    primaryAction: '进入列表',
    primaryItems: [
      ['东区门店平板即将过保', '共有 14 台设备在 30 天内进入保修截止窗口。', '资产团队 · 今天', '维保预警', 'warning'],
      ['授权池需要补充', '分析工具授权的余量不足以覆盖新项目组，建议尽快追加采购。', 'IT 运营 · 11:40', '需采购', 'brand'],
    ],
    secondaryTitle: '盘点动作',
    secondaryAction: '生成盘点单',
    secondaryItems: [
      ['季度盘点单已生成', '系统按空间和管理组拆分批次，适合分派给区域管理员。', '资产运营 · 自动生成', '已就绪', 'success'],
      ['历史资产待归档', '上季度下线对象仍有 32 条未补归档说明。', '审计团队 · 待补充', '待清理', 'warning'],
    ],
    asideTitle: '台账上下文',
    asideDescription: '放规则、时效和归档窗口。',
    asideItems: [['折旧周期', '硬件 36 个月，软件 12 个月', '规则', 'brand'], ['盘点频率', '高价值资产按月检查', '稳定', 'success'], ['归档窗口', '每周三统一处理', '需跟进', 'warning']],
    notes: ['资产页更适合目录和生命周期动作，不需要营销式资源卡片。', '盘点与维保应在同一主线内可见。'],
  }),
  'support-desk': buildFoundationScenario({
    eyebrow: 'Support Desk',
    title: '客服支持台',
    description: '验证工单队列、客户上下文和处理模板在客服工作面中的组合方式。',
    emphasis: '工单与客户上下文',
    railTitle: '支持域',
    railDescription: '共享基座中的客服与支持工作面样板。',
    railItems: [['开放工单', '按 SLA 排序', true], ['高风险客户', '重点跟进'], ['知识模板', '回复片段'], ['交班', '当班记录']],
    badges: [['Foundation', 'brand', 'filled'], ['支持工作面'], ['高频操作']],
    heroTitle: '客服台的重点是队列、客户背景和可直接执行的下一步动作。',
    heroBody: '让工单和客户上下文并排可见，能避免客服来回切多个页面确认背景。',
    heroSupport: '适合一线支持、客户成功和升级处理页。',
    stats: [['开放工单', '146', 'brand'], ['SLA 达标', '96%', 'success'], ['高风险客户', '11', 'warning']],
    primaryTitle: '待处理工单',
    primaryAction: '查看全部',
    primaryItems: [
      ['企业租户无法访问权限页', '用户反馈角色调整后仍看不到页面，建议先核对团队包和角色包交集。', '工单 #41028 · 刚刚', '待处理', 'brand'],
      ['账单导出延迟', '导出任务在高峰期排队时间过长，需要先给客户同步预计完成时间。', '工单 #41011 · 18 分钟前', '需同步', 'warning'],
    ],
    secondaryTitle: '处理模板',
    secondaryAction: '打开知识库',
    secondaryItems: [
      ['权限裁剪解释模板', '适合解释菜单、页面和功能包裁剪结果，不再引用旧按钮权限说法。', '模板库 · 已发布', '可复用', 'success'],
      ['升级工单交接单', '夜班值守需要在升级前补充当前影响面和客户联系人。', '交接模板 · 推荐', '建议使用', 'brand'],
    ],
    asideTitle: '客户上下文',
    asideDescription: '低频背景信息只放在侧栏，不占主队列视线。',
    asideItems: [['企业版客户', '占当前队列 42%', '稳定', 'success'], ['重点行业', '金融与零售需优先跟进', '提醒', 'warning'], ['交班时间', '每日 19:00 自动生成简报', '规则', 'brand']],
    notes: ['支持台不要把模板和说明挤到主队列上方。', 'SLA 和风险客户信息应辅助队列，而不是抢过队列本身。'],
  }),
  'search-workspace': buildFoundationScenario({
    eyebrow: 'Search Workspace',
    title: '全局检索台',
    description: '验证统一搜索、筛选脉络和结果上下文在高密度后台中的表达。',
    emphasis: '搜索与结果理解',
    railTitle: '检索域',
    railDescription: '适合“搜索即主任务”的工作面。',
    railItems: [['最近搜索', '高频关键词', true], ['筛选维度', '按域拆分'], ['结果类型', '菜单、页面、用户'], ['保存视图', '团队常用']],
    badges: [['Foundation', 'brand', 'filled'], ['搜索工作台'], ['跨域检索']],
    heroTitle: '检索台要先交代结果覆盖范围和筛选维度，而不是只放一个大输入框。',
    heroBody: '把最近搜索、结果类型和保存视图放到同一工作面，更适合企业后台持续使用。',
    heroSupport: '适合运维检索、配置查找和运营后台全局搜索。',
    stats: [['索引对象', '1.2M', 'brand'], ['平均响应', '320ms', 'success'], ['保存视图', '28', 'warning']],
    primaryTitle: '最近结果',
    primaryAction: '查看详情',
    primaryItems: [
      ['menu spaces 命中 18 条', '菜单空间、导航治理和运行时空间切换结果已按类型分组。', '搜索词：menu spaces', '命中高', 'success'],
      ['权限裁剪命中 34 条', '角色包、团队包和隐藏菜单相关结果建议按后端接口域继续收窄。', '搜索词：permission binding', '需收窄', 'warning'],
    ],
    secondaryTitle: '结果理解',
    secondaryAction: '保存视图',
    secondaryItems: [
      ['按对象类型拆分结果', '菜单、页面、用户和接口的命中结果应分组呈现，避免扁平长列表。', '检索体验 · 推荐模式', '推荐', 'brand'],
      ['保留最近筛选快照', '相同问题经常重复检索，保存视图比重新配置筛选更高效。', '搜索体验 · 建议', '建议', 'success'],
    ],
    asideTitle: '检索规则',
    asideDescription: '右栏只放规则和索引状态。',
    asideItems: [['索引延迟', '最近一次刷新在 3 分钟前', '新鲜', 'success'], ['跨域搜索', '支持菜单 / 页面 / 用户', '范围', 'brand'], ['保存视图', '团队可共享常用检索面板', '协作', 'warning']],
    notes: ['搜索页的主任务是帮助理解结果，不只是展示命中数量。', '筛选、类型和结果上下文应该一并出现。'],
  }),
  'release-control': buildFoundationScenario({
    eyebrow: 'Release Control',
    title: '发布控制台',
    description: '验证发布批次、风险窗口、回滚点和负责人在控制台中的表达。',
    emphasis: '发布批次与回滚',
    railTitle: '发布域',
    railDescription: '适合灰度发布、环境窗口和版本控制工作台。',
    railItems: [['批次', '环境与窗口', true], ['风险', '回滚点'], ['校验', '检查项'], ['广播', '发布同步']],
    badges: [['Foundation', 'brand', 'filled'], ['发布控制'], ['高风险动作', 'warning']],
    heroTitle: '发布控制台的首屏必须交代当前批次、风险级别和能否回滚。',
    heroBody: '控制台不是普通统计页，它应该让负责人快速判断是继续放量还是立即暂停。',
    heroSupport: '适合环境发布、灰度放量和系统升级页。',
    stats: [['当前批次', 'B-12', 'brand'], ['通过检查', '28', 'success'], ['待确认', '4', 'warning']],
    primaryTitle: '当前批次',
    primaryAction: '查看清单',
    primaryItems: [
      ['生产批次 B-12 正在放量', '已完成首批租户放量，当前等待二批风险确认后继续。', '发布团队 · 刚刚', '进行中', 'brand'],
      ['回滚点已冻结', '关键依赖版本与配置快照均已记录，可在 5 分钟内回退。', '环境平台 · 10 分钟前', '可回滚', 'success'],
    ],
    secondaryTitle: '发布风险',
    secondaryAction: '打开广播草稿',
    secondaryItems: [
      ['接口兼容提醒待发送', '有 3 个租户依赖旧字段返回，建议在扩大发布前补通知。', '兼容性检查 · 待发送', '需广播', 'warning'],
      ['夜间窗口校验未结束', '数据库慢查询观察窗还需要 12 分钟，期间不建议放量。', '值守观察 · 倒计时', '等待中', 'brand'],
    ],
    asideTitle: '发布背景',
    asideDescription: '保留回滚、值守和广播规则。',
    asideItems: [['广播窗口', '对外通知在每批次开始前 15 分钟', '规则', 'brand'], ['回滚 SLA', '5 分钟内恢复上一稳定版本', '稳定', 'success'], ['值守覆盖', '夜间需双人确认', '必需', 'warning']],
    notes: ['发布页要把是否继续放量作为最强决策点。', '风险、检查和广播应该围绕同一批次展示。'],
  }),
  'knowledge-hub': buildFoundationScenario({
    eyebrow: 'Knowledge Hub',
    title: '知识中枢',
    description: '验证知识文档、操作手册和常见流程在 Fluent 2 下的低噪布局。',
    emphasis: '知识与操作手册',
    railTitle: '知识入口',
    railDescription: '适合把文档和执行流程并列展示的后台知识页。',
    railItems: [['热门手册', '高频使用', true], ['流程卡片', '执行步骤'], ['更新日志', '最近变化'], ['维护人', '责任人']],
    badges: [['Foundation', 'brand', 'filled'], ['知识中心'], ['文档工作面']],
    heroTitle: '知识页的重点不是卡片数量，而是帮助用户快速找到“下一份该看的文档”。',
    heroBody: '把高频手册、推荐流程和最近变化放在同一页，更适合作为支持型工作面。',
    heroSupport: '适合内部知识库、操作手册和治理文档入口页。',
    stats: [['手册总数', '214', 'brand'], ['本周更新', '18', 'success'], ['待审核', '7', 'warning']],
    primaryTitle: '推荐手册',
    primaryAction: '打开目录',
    primaryItems: [
      ['菜单治理联调手册', '说明 Menu、UIPage 和空间切换相关接口的定位方式。', '平台文档 · 今天更新', '推荐', 'success'],
      ['权限裁剪排障指引', '专门解释团队包、角色包和隐藏菜单的运行时差异。', '权限文档 · 本周高频', '高频', 'brand'],
    ],
    secondaryTitle: '最近变化',
    secondaryAction: '查看全部更新',
    secondaryItems: [
      ['导航接口说明补充完成', '新增 menu spaces 与 runtime navigation 的联调用法。', '变更日志 · 2 小时前', '已发布', 'success'],
      ['角色页迁移说明待审核', 'React 侧治理页的二期方案已提交，等待评审。', '迁移专题 · 待审核', '待确认', 'warning'],
    ],
    asideTitle: '知识规则',
    asideDescription: '右栏放责任人、审核和使用范围。',
    asideItems: [['维护人', '按专题绑定 owner', '规则', 'brand'], ['审核周期', '核心手册每月复核', '稳定', 'success'], ['适用范围', '仅保留当前有效专题', '提醒', 'warning']],
    notes: ['知识页更适合把“推荐入口”和“最近变化”并排，而不是做成纯资源墙。', '优先帮助用户找到下一份要看的内容。'],
  }),
} as const;

export const fluentScenarioData = {
  'shell-guidelines': buildFluentScenario({
    eyebrow: 'Fluent 2 Web',
    title: '应用壳规范页',
    description: '偏文档式工作区，验证应用壳、导航宽度与主工作区节奏的规范表达。',
    emphasis: '应用壳文档化',
    badges: [['Microsoft Fluent 2 Web', 'brand', 'filled'], ['Layout spec'], ['Design-to-dev']],
    stats: [['布局样例', '8', 'brand'], ['适配断点', '4', 'success'], ['注意事项', '12', 'warning']],
    navTitle: 'Shell anatomy',
    navItems: [['Top bar', '命令区与品牌位'], ['Navigation', '侧栏与层级'], ['Workspace', '主工作区'], ['Inspector', '次级上下文']],
    docTitle: 'Application shell',
    docBody: '把顶部栏、导航区和主工作区做成一张文档式参考页，更适合团队统一应用壳的语法和密度。',
    docLinks: ['View documentation', 'Engineering assets'],
    docNotes: ['重点看左栏宽度、标题区和右侧辅助面板如何分层。'],
    variantTitle: 'Shell variants',
    variantAction: 'View examples',
    variants: [['Compact shell', '适合高密度工作台', 'Open spec', true], ['Guide mode', '适合文档类工作区', 'Preview'], ['Rail focus', '适合导航优先型应用', 'Inspect']],
    specimens: [
      ['壳层规则', '聚焦导航、标题和工作区的结构说明。', ['顶部栏只承载全局操作。', '侧栏负责模块切换，不堆低频动作。', '右栏信息不与主区抢层级。']],
      ['实现建议', '面向 React Fluent 2 基座的落地建议。', ['优先用共享 token 收口。', '保持内容区和次级面板的节奏稳定。', '避免为单页发明额外壳层。']],
      ['适用范围', '更适合作为团队统一参考。', ['治理页', '运营工作台', '设置中心']],
      ['联调注意', '设计与实现交接时最容易偏差的点。', ['导航宽度', '标题区留白', '响应式折叠']],
    ],
  }),
  'data-grid-spec': buildFluentScenario({
    eyebrow: 'Fluent 2 Web',
    title: '数据网格规范',
    description: '验证 DataGrid、筛选区、工具栏和右侧详情在文档式页面中的说明结构。',
    emphasis: 'DataGrid 规范',
    badges: [['Microsoft Fluent 2 Web', 'brand', 'filled'], ['DataGrid'], ['Spec page']],
    stats: [['列模式', '6', 'brand'], ['行状态', '9', 'success'], ['交互提醒', '11', 'warning']],
    navTitle: 'Grid patterns',
    navItems: [['Toolbar', '主操作与批量动作'], ['Density', '行高与阅读感'], ['Status', '标签与异常'], ['Inspector', '右侧详情']],
    docTitle: 'Data grid guidance',
    docBody: '这类页强调“如何组织筛选、表格和详情”而不是只罗列控件外观，适合作为工作台设计规范。',
    docLinks: ['View documentation', 'Pattern notes'],
    docNotes: ['优先说明阅读顺序、状态优先级和行级动作的收口。'],
    variantTitle: 'Grid variants',
    variantAction: 'Open patterns',
    variants: [['Review grid', '适合审批和校验', 'Open spec', true], ['Explorer grid', '适合资产和资源列表', 'Preview'], ['Queue grid', '适合事件和工单队列', 'Inspect']],
    specimens: [
      ['工具栏规则', '高频动作靠前，低频动作收纳。', ['主按钮只保留一个。', '批量动作靠近筛选区。', '刷新与导出应次级表达。']],
      ['状态表达', '标签和内联提示不要抢过表格内容。', ['先看行状态，再看图标。', '危险态需要颜色与文案双重提示。']],
      ['详情侧栏', '适合放属性、时间线和低频说明。', ['不要复制表格字段。', '保持右栏低噪音。']],
      ['响应式', '平板与窄屏下需要收口列数。', ['先折叠低频列。', '再转为上下详情布局。']],
    ],
  }),
  'form-patterns': buildFluentScenario({
    eyebrow: 'Fluent 2 Web',
    title: '表单模式库',
    description: '偏规范页，验证分组表单、保存反馈和风险操作在 Fluent 2 文档语法中的组织方式。',
    emphasis: '表单结构与反馈',
    badges: [['Microsoft Fluent 2 Web', 'brand', 'filled'], ['Form patterns'], ['Authoring']],
    stats: [['Section 模式', '5', 'brand'], ['反馈层级', '4', 'success'], ['危险动作', '6', 'warning']],
    navTitle: 'Form language',
    navItems: [['Sections', '分组和摘要'], ['Actions', '保存与取消'], ['Validation', '错误与说明'], ['Danger', '删除与确认']],
    docTitle: 'Form structure guidance',
    docBody: '表单页更应该被描述为“结构和反馈系统”，而不是一串字段。规范页重点在分组、错误和危险动作分层。',
    docLinks: ['View documentation', 'Implementation notes'],
    docNotes: ['适合把设置页、详情编辑和抽屉表单统一到一套语法。'],
    variantTitle: 'Form variants',
    variantAction: 'Browse recipes',
    variants: [['Long-form settings', '适合设置中心', 'Open guide', true], ['Drawer edit', '适合轻编辑', 'Preview'], ['Review form', '适合审批校验', 'Inspect']],
    specimens: [
      ['分组策略', '每个 section 只承担一个主任务。', ['标题解释范围。', '说明文本解释后果。', '不要把所有字段堆成一屏。']],
      ['反馈层级', '内联错误、局部消息和全局通知必须区分。', ['错误靠近字段。', '保存结果可用顶部消息条承接。']],
      ['危险动作', '删除、停用和撤销需要明确分区。', ['不要和保存按钮并列混排。', '确认内容必须说明影响对象。']],
      ['辅助上下文', '说明、历史记录和帮助可放在侧栏。', ['不要挤进字段区。', '低频信息弱化呈现。']],
    ],
  }),
  'navigation-spec': buildFluentScenario({
    eyebrow: 'Fluent 2 Web',
    title: '导航结构规范',
    description: '验证左侧导航、层级展开和当前页定位在文档式说明页中的表达。',
    emphasis: '导航层级',
    badges: [['Microsoft Fluent 2 Web', 'brand', 'filled'], ['Navigation'], ['Hierarchy']],
    stats: [['导航层级', '4', 'brand'], ['定位模式', '3', 'success'], ['错误案例', '7', 'warning']],
    navTitle: 'Navigation anatomy',
    navItems: [['Hierarchy', '一级与二级关系'], ['Current state', '高亮与定位'], ['Overflow', '折叠与收纳'], ['Context', '标题与路径']],
    docTitle: 'Navigation structure',
    docBody: '导航规范页适合解释“哪些内容留在侧栏，哪些内容进入标题区”，从而避免不同页面各自发明一套导航语法。',
    docLinks: ['View documentation', 'Navigation notes'],
    docNotes: ['核心是让人一眼知道自己在哪个层级，而不是做更多装饰。'],
    variantTitle: 'Navigation variants',
    variantAction: 'Open guidance',
    variants: [['Workbench nav', '适合工作台', 'Open spec', true], ['Settings nav', '适合设置中心', 'Preview'], ['Explorer nav', '适合目录型页面', 'Inspect']],
    specimens: [
      ['定位原则', '当前页高亮必须稳定。', ['不要把路径提示藏在低对比度区域。', '面包屑和侧栏职责不同。']],
      ['折叠策略', '优先折叠低频分组，而不是挤压标签。', ['窄屏时改成抽屉。', '保持导航语义不变。']],
      ['标题联动', '标题区要补全侧栏无法表达的上下文。', ['适合放摘要和操作。', '不重复导航标签。']],
      ['错误案例', '规范页也要明确不推荐的做法。', ['不要堆三层以上层级。', '不要把按钮混进导航树。']],
    ],
  }),
  'token-governance': buildFluentScenario({
    eyebrow: 'Fluent 2 Web',
    title: 'Token 治理台',
    description: '偏规范与治理结合页，验证颜色、间距和状态 token 的文档化展示。',
    emphasis: 'Token 与主题治理',
    badges: [['Microsoft Fluent 2 Web', 'brand', 'filled'], ['Tokens'], ['Theme']],
    stats: [['颜色层级', '14', 'brand'], ['间距级别', '8', 'success'], ['主题模式', '2', 'warning']],
    navTitle: 'Token categories',
    navItems: [['Color', '前景、背景与状态'], ['Spacing', '节奏与密度'], ['Radius', '圆角规则'], ['Theme', '亮暗切换']],
    docTitle: 'Token governance',
    docBody: '这类页适合把设计 token 从抽象名称拉回到真实界面语义，让前端和设计都能按页面层级理解它们的用途。',
    docLinks: ['View documentation', 'Theme assets'],
    docNotes: ['重点是“token 影响了哪种页面层级”，不是只列值。'],
    variantTitle: 'Token specimens',
    variantAction: 'Inspect values',
    variants: [['Brand surfaces', '品牌与主动作', 'Open spec', true], ['Neutral system', '背景与表层', 'Preview'], ['Status semantics', '成功 / 警告 / 危险', 'Inspect']],
    specimens: [
      ['颜色分层', '说明不同背景和前景的使用边界。', ['主背景保持低噪。', '品牌色只用在关键行动和焦点。']],
      ['间距节奏', '页面密度靠间距系统收口。', ['先统一 section 间距。', '再决定组件内边距。']],
      ['主题切换', '亮暗模式应该共享结构，不共享硬编码色值。', ['不要暗色里夹白底。', '优先 token 驱动。']],
      ['交接建议', '设计与代码都要看语义而不是裸值。', ['把 token 挂到组件用途。', '减少局部特例。']],
    ],
  }),
  'accessibility-review': buildFluentScenario({
    eyebrow: 'Fluent 2 Web',
    title: '可访问性评审',
    description: '验证焦点态、对比度、键盘流与状态说明如何形成规范页。',
    emphasis: 'A11y 评审基线',
    badges: [['Microsoft Fluent 2 Web', 'brand', 'filled'], ['Accessibility'], ['Review']],
    stats: [['焦点规则', '9', 'brand'], ['对比度项', '7', 'success'], ['键盘路径', '5', 'warning']],
    navTitle: 'Accessibility checks',
    navItems: [['Focus', '焦点边框与顺序'], ['Contrast', '前景与背景'], ['Keyboard', 'Tab 流和逃生'], ['Feedback', '状态说明']],
    docTitle: 'Accessibility review guidance',
    docBody: '这张页强调“如何检查页面是否真的可用”，比纯视觉页更适合作为前端验收和设计评审的共同语言。',
    docLinks: ['View documentation', 'Review checklist'],
    docNotes: ['适合把焦点态、禁用态和危险动作提示统一成显式规则。'],
    variantTitle: 'Review sets',
    variantAction: 'Open checklist',
    variants: [['Form review', '适合字段和错误', 'Open set', true], ['Grid review', '适合表格与列表', 'Preview'], ['Shell review', '适合应用壳与导航', 'Inspect']],
    specimens: [
      ['焦点顺序', '需要覆盖标题区、导航、表单和对话框。', ['键盘路径不能跳层。', '焦点样式必须可见。']],
      ['对比度', '状态色不能只靠色相区分。', ['正文和背景优先满足可读性。', '次级文案也不能过轻。']],
      ['反馈提示', '危险动作和错误状态需要明确的文字说明。', ['不要只给红色。', '给出后果和下一步。']],
      ['验收方式', '适合作为工程与设计共同检查单。', ['桌面端', '平板端', '窄屏模式']],
    ],
  }),
  'handoff-patterns': buildFluentScenario({
    eyebrow: 'Fluent 2 Web',
    title: 'Handoff 模式页',
    description: '验证设计到开发交接中，说明、预览与工程入口如何组织成一页。',
    emphasis: 'Design-to-dev handoff',
    badges: [['Microsoft Fluent 2 Web', 'brand', 'filled'], ['Handoff'], ['Engineering assets']],
    stats: [['交接块', '5', 'brand'], ['工程入口', '4', 'success'], ['说明层级', '8', 'warning']],
    navTitle: 'Handoff building blocks',
    navItems: [['Spec', '核心说明'], ['Preview', '参考画面'], ['Assets', '工程入口'], ['Notes', '实现提醒']],
    docTitle: 'Handoff pattern',
    docBody: '交接页的重点是帮助前端快速找到“应该实现什么、哪些是强约束、哪些是参考层”，而不是只贴几张截图。',
    docLinks: ['View documentation', 'Engineering assets'],
    docNotes: ['建议把 Figma 节点、实现提示和可访问性约束放在同一页。'],
    variantTitle: 'Handoff packs',
    variantAction: 'Inspect package',
    variants: [['Page handoff', '适合整页交接', 'Open pack', true], ['Component handoff', '适合组件细节', 'Preview'], ['Review handoff', '适合评审复核', 'Inspect']],
    specimens: [
      ['交接结构', '先说明任务，再说明参考。', ['标题与范围', '节点与约束', '工程入口']],
      ['截图角色', '截图只做视觉核对，不作为唯一内容来源。', ['先看结构。', '再看视觉。']],
      ['工程资产', '前端需要知道哪些文件、哪些 token、哪些组件。', ['不要只给图片。', '给出实现路径。']],
      ['评审收口', '交接页也要说明未定项。', ['明确假设。', '避免静默脑补。']],
    ],
  }),
  'template-gallery': buildFluentScenario({
    eyebrow: 'Fluent 2 Web',
    title: '模板画廊',
    description: '偏模板索引页，验证页面骨架、模式卡和推荐用法的文档式组织。',
    emphasis: '模板与模式索引',
    badges: [['Microsoft Fluent 2 Web', 'brand', 'filled'], ['Templates'], ['Pattern library']],
    stats: [['模板数', '16', 'brand'], ['适用场景', '9', 'success'], ['推荐组合', '12', 'warning']],
    navTitle: 'Template categories',
    navItems: [['Workbenches', '运营与治理'], ['Forms', '设置与编辑'], ['Messaging', '消息与通知'], ['Specs', '说明与规范']],
    docTitle: 'Template gallery',
    docBody: '模板画廊适合帮助团队快速对齐“这类页面该从哪个骨架起步”，比单独找零散页面更高效。',
    docLinks: ['Browse gallery', 'Pattern notes'],
    docNotes: ['适合作为 Fluent 2 React 实验场的目录型说明页。'],
    variantTitle: 'Template families',
    variantAction: 'Open gallery',
    variants: [['Workbench set', '运营工作台骨架', 'Open set', true], ['Spec set', '说明与规范骨架', 'Preview'], ['Collab set', '协作与消息骨架', 'Inspect']],
    specimens: [
      ['模板选择', '按主任务选择骨架，而不是按视觉偏好。', ['先判断是列表、表单还是协作。', '再决定次级面板形式。']],
      ['组合建议', '模板之间可共享基座与 token。', ['共享标题区。', '共享状态反馈。']],
      ['不推荐做法', '避免每次新页面都从空白画布开始。', ['减少随机布局。', '提高一致性。']],
      ['实验场作用', '画廊页本身也是检索入口。', ['适合后续扩到更多治理页。']],
    ],
  }),
  'motion-principles': buildFluentScenario({
    eyebrow: 'Fluent 2 Web',
    title: '动效原则页',
    description: '验证页面进入、展开收起和反馈动效如何用说明页收口，不让动效变成噪音。',
    emphasis: '动效与焦点迁移',
    badges: [['Microsoft Fluent 2 Web', 'brand', 'filled'], ['Motion'], ['Focus']],
    stats: [['进入动效', '3', 'brand'], ['反馈类型', '4', 'success'], ['禁忌项', '6', 'warning']],
    navTitle: 'Motion layers',
    navItems: [['Entrance', '页面进入'], ['Reveal', '展开与显示'], ['Feedback', '完成与失败'], ['Reduce', '何时删减']],
    docTitle: 'Motion principles',
    docBody: '动效页更适合解释“动效为什么存在”，即帮助理解层级变化和焦点迁移，而不是追求装饰。',
    docLinks: ['View guidance', 'Motion notes'],
    docNotes: ['动效应服务理解，不服务炫技。'],
    variantTitle: 'Motion specimens',
    variantAction: 'Open examples',
    variants: [['Page enter', '首屏进入', 'Open guide', true], ['Panel transition', '面板进出', 'Preview'], ['Inline feedback', '局部反馈', 'Inspect']],
    specimens: [
      ['进入节奏', '用于帮助建立页面层级。', ['标题先于内容。', '大区块不要同时抢入场。']],
      ['展开收起', '用于说明区域关系变化。', ['抽屉、树、说明块更适合轻动效。']],
      ['反馈动效', '完成和失败都需要明确节奏。', ['Toast 不宜喧宾夺主。', '状态变化要可被感知。']],
      ['减法原则', '如果动效不提升理解，就删掉。', ['尤其是后台工作台。']],
    ],
  }),
  'sidepanel-reference': buildFluentScenario({
    eyebrow: 'Fluent 2 Web',
    title: '侧板参考页',
    description: '验证右侧属性板、详情抽屉和辅助面板的文档化参考布局。',
    emphasis: '侧板与主工作区',
    badges: [['Microsoft Fluent 2 Web', 'brand', 'filled'], ['Side panel'], ['Inspector']],
    stats: [['侧板模式', '4', 'brand'], ['信息层级', '6', 'success'], ['交互提醒', '5', 'warning']],
    navTitle: 'Inspector patterns',
    navItems: [['Properties', '属性与状态'], ['History', '时间线与记录'], ['Help', '说明与引导'], ['Actions', '低频操作']],
    docTitle: 'Side panel reference',
    docBody: '侧板参考页重点说明什么信息应该留在主工作区，什么信息适合进入右侧辅助面板，从而保持主次分明。',
    docLinks: ['View documentation', 'Layout assets'],
    docNotes: ['避免把所有字段复制一份到右栏。'],
    variantTitle: 'Side panel variants',
    variantAction: 'Open references',
    variants: [['Property rail', '适合详情属性', 'Open spec', true], ['Timeline rail', '适合审计与历史', 'Preview'], ['Helper rail', '适合说明和风险', 'Inspect']],
    specimens: [
      ['属性面板', '适合稳定但低频查看的信息。', ['元信息', '状态', '归属']],
      ['时间线面板', '适合审计、操作记录和变更历史。', ['不要覆盖主编辑区。']],
      ['帮助面板', '适合规则、提示和风险说明。', ['只保留低频辅助信息。']],
      ['布局原则', '主工作区仍然承担主任务。', ['右栏不抢主标题。']],
    ],
  }),
} as const;

export const teamsScenarioData = {
  'meeting-command': buildTeamsScenario({
    eyebrow: 'Meeting Command',
    title: '会议指挥页',
    description: '验证会议编排、主持人上下文和会中任务在 Teams 风格下的协作页面表达。',
    emphasis: '会议协作与会中动作',
    badges: [['Teams line', 'brand', 'filled'], ['Meeting'], ['协调工作面']],
    channelTitle: 'Executive review',
    channelDescription: '偏会议和协作节奏，不直接复刻聊天产品。',
    channelItems: [['会前准备', '资料与嘉宾'], ['议程协同', '主持和顺序', true], ['行动项', '会后跟进'], ['复盘', '决议与总结']],
    heroTitle: '会议页要把议程、责任人和会中动作压到一个能快速决策的工作面。',
    heroBody: '用频道式组织方式收纳会议上下文，能比普通日历页更好承接会前、会中和会后动作。',
    heroSupport: '适合周会、评审会和高层例会的协作工作面。',
    stats: [['待确认议程', '6', 'brand'], ['在线参与者', '14', 'success'], ['会后动作', '9', 'warning']],
    feedTitle: '会中更新',
    feedAction: '查看纪要',
    feedItems: [
      ['主持人已锁定议程顺序', '前两项讨论时间已延长，建议把低优先级议题移到补充议程。', '主持人 · 刚刚', '会中调整', 'brand'],
      ['财务段落材料已补齐', '最新预算截图已同步到会议附件，可直接投屏展示。', '运营协调 · 12 分钟前', '已准备', 'success'],
    ],
    taskTitle: '会议动作',
    taskAction: '导出行动项',
    taskItems: [
      ['会后纪要待整理', '系统已自动生成决议草稿，仍需补充责任人和截止日期。', '纪要助手 · 待确认', '待完成', 'warning'],
      ['关键风险需会后升级', '两项预算风险超出会议决策范围，需要转给治理频道继续跟进。', '战略项目组 · 待转办', '需升级', 'brand'],
    ],
    membersTitle: '与会角色',
    membersDescription: '右栏只保留人和职责，不重复会议流内容。',
    memberItems: [['主持人', '负责议程推进', '在线', 'success'], ['记录员', '负责纪要与行动项', '同步中', 'brand'], ['财务代表', '负责预算问题', '待发言', 'warning']],
    notes: ['Teams 会议页应该强调协作节奏和角色，不强调营销式主视觉。', '主工作区先放更新流和动作，不先放成员列表。'],
  }),
  'frontline-briefing': buildTeamsScenario({
    eyebrow: 'Frontline Briefing',
    title: '一线简报台',
    description: '验证班前简报、重点提醒和轮班同步在 Teams 协作布局中的表达。',
    emphasis: '班前同步和简报',
    badges: [['Teams line', 'brand', 'filled'], ['Frontline'], ['Briefing']],
    channelTitle: 'Morning brief',
    channelDescription: '更偏一线团队和轮班节奏。',
    channelItems: [['今日重点', '必读摘要', true], ['门店反馈', '现场更新'], ['排班', '人员覆盖'], ['升级事项', '需总部支持']],
    heroTitle: '简报台更适合作为“开班前 3 分钟就能扫完”的协作页面。',
    heroBody: '先交代今日关键指标、门店提醒和需要升级的事项，而不是做复杂分析图表。',
    heroSupport: '适合门店、一线支持和现场执行团队。',
    stats: [['今日提醒', '8', 'brand'], ['覆盖门店', '42', 'success'], ['升级事项', '3', 'warning']],
    feedTitle: '今日简报',
    feedAction: '查看全部',
    feedItems: [
      ['天气影响已同步到配送班次', '东区强降雨门店已调整到低频配送节奏，建议门店经理留意冷链库存。', '总部值班 · 今天 07:30', '已同步', 'success'],
      ['新品陈列执行需要加派人手', '两家重点门店反馈上架工作量超预期，建议店长提早安排二次排班。', '区域运营 · 今天 08:10', '需跟进', 'warning'],
    ],
    taskTitle: '升级事项',
    taskAction: '发送总部',
    taskItems: [
      ['西区门店网络不稳定', '可能影响收银和库存回传，建议 IT 值班今日优先处理。', '门店 IT · 待派单', '需升级', 'brand'],
      ['早班覆盖不足', '三家门店请假集中，需要调拨兼岗人员。', '区域调度 · 待协调', '待确认', 'warning'],
    ],
    membersTitle: '轮班角色',
    membersDescription: '侧栏保留轮班与责任链信息。',
    memberItems: [['区域经理', '负责升级事项', '在线', 'success'], ['店长群组', '负责现场执行', '同步中', 'brand'], ['IT 值班', '负责设备异常', '待响应', 'warning']],
    notes: ['一线简报更适合短文案和强结论，不适合过长解释。', '把简报和升级事项放在同一工作面更符合班前节奏。'],
  }),
  'file-collaboration': buildTeamsScenario({
    eyebrow: 'File Collaboration',
    title: '文件协作台',
    description: '验证文件讨论、审阅流和共享资料侧栏在 Teams 风格下的页面组合。',
    emphasis: '文件审阅与讨论',
    badges: [['Teams line', 'brand', 'filled'], ['Files'], ['Review']],
    channelTitle: 'Launch assets',
    channelDescription: '把文件流、评论和审阅动作组织成协作页面。',
    channelItems: [['全部文件', '最近共享'], ['审阅中', '待确认素材', true], ['已通过', '可发布'], ['归档', '历史版本']],
    heroTitle: '文件协作页的关键不是像网盘，而是像“围绕文件做决策”的工作面。',
    heroBody: '把审阅流、责任人和版本状态放在一起，能帮助团队减少在聊天和网盘之间来回跳转。',
    heroSupport: '适合素材审阅、提案协同和跨团队文件确认。',
    stats: [['审阅中文件', '19', 'brand'], ['已通过', '43', 'success'], ['待补材料', '5', 'warning']],
    feedTitle: '审阅更新',
    feedAction: '查看版本',
    feedItems: [
      ['新品 KV 第三版待最终确认', '设计团队已按反馈修改标题区，建议市场 owner 直接在此页确认是否发布。', '设计团队 · 20 分钟前', '待确认', 'warning'],
      ['门店素材已归组完成', '各区域文件按渠道和门店类型拆分，适合直接分发到执行频道。', '运营支持 · 今天 09:10', '已整理', 'success'],
    ],
    taskTitle: '协作动作',
    taskAction: '创建审阅任务',
    taskItems: [
      ['法务审批待插队处理', '一份对外物料需优先审查免责声明，建议临时提升审批优先级。', '法务联席 · 待插队', '需升级', 'brand'],
      ['摄影原图待补充', '直播物料的原始素材缺失 2 张，需要联系供应商补齐。', '内容运营 · 待补', '待补充', 'warning'],
    ],
    membersTitle: '协作角色',
    membersDescription: '右侧栏只放人和职责。',
    memberItems: [['市场 owner', '负责最终发布', '在线', 'success'], ['设计团队', '负责版本迭代', '同步中', 'brand'], ['法务', '负责合规审阅', '待确认', 'warning']],
    notes: ['文件协作页的主线是“围绕文件做动作”，不是展示缩略图墙。', '右侧栏适合放角色，不适合再放文件列表。'],
  }),
  'approval-conversation': buildTeamsScenario({
    eyebrow: 'Approval Conversation',
    title: '审批会话页',
    description: '验证审批线程、上下文说明和责任人评论在 Teams 语法下的收口。',
    emphasis: '审批与会话',
    badges: [['Teams line', 'brand', 'filled'], ['Approval'], ['Conversation']],
    channelTitle: 'Approval thread',
    channelDescription: '适合把审批流程和沟通放在同一个页面。',
    channelItems: [['待审批', '需要动作', true], ['已批复', '结果回顾'], ['驳回', '需修改'], ['归档', '历史审批']],
    heroTitle: '审批页可以借用 Teams 的线程表达，但重点仍是审批状态和下一步动作。',
    heroBody: '把评论、责任人和审批理由放在一起，比把审批当成单独表单更利于协作判断。',
    heroSupport: '适合预算审批、策略审批和跨部门确认页。',
    stats: [['待审批', '14', 'brand'], ['已完成', '27', 'success'], ['超时风险', '4', 'warning']],
    feedTitle: '审批讨论',
    feedAction: '展开全部',
    feedItems: [
      ['预算审批进入最终确认', '财务和业务 owner 的意见已对齐，当前等待负责人最终批复。', '审批线程 · 刚刚', '最后一步', 'brand'],
      ['风控规则变更被要求补充例外说明', '当前讨论集中在高价值客户是否需要保留人工白名单。', '安全委员会 · 30 分钟前', '需补充', 'warning'],
    ],
    taskTitle: '后续动作',
    taskAction: '转成任务',
    taskItems: [
      ['审批结果需要同步到治理页', '通过后需更新策略工作室中的正式版本与生效时间。', '平台策略 · 待同步', '待同步', 'brand'],
      ['补件模板待发送', '驳回场景需要向申请人发送补件清单。', '审批支持 · 未发送', '待完成', 'warning'],
    ],
    membersTitle: '审批角色',
    membersDescription: '右栏放审批责任链即可。',
    memberItems: [['申请人', '负责补件与说明', '待反馈', 'warning'], ['审批 owner', '负责最终决定', '在线', 'success'], ['审阅组', '负责意见整合', '同步中', 'brand']],
    notes: ['审批页可以使用线程，但核心仍是审批状态而不是聊天感。', '审批理由、评论和动作建议保持在一个主工作区里。'],
  }),
  'onboarding-hub': buildTeamsScenario({
    eyebrow: 'Onboarding Hub',
    title: '入职协作台',
    description: '验证入职任务、欢迎流和责任人协作在 Teams 风格页面中的表达。',
    emphasis: '入职协同',
    badges: [['Teams line', 'brand', 'filled'], ['Onboarding'], ['Collaboration']],
    channelTitle: 'New joiners',
    channelDescription: '偏人和流程的协作中心。',
    channelItems: [['欢迎流', '新人节奏', true], ['设备与账号', '准备清单'], ['导师', '支持安排'], ['反馈', '首周回顾']],
    heroTitle: '入职协作页更适合把任务、欢迎说明和导师职责合在一起。',
    heroBody: '它不是 HR 纯流程表，而是围绕新人的协作面，让相关角色都知道下一步要做什么。',
    heroSupport: '适合 IT、HRBP 和直属经理联合使用。',
    stats: [['本周新人', '12', 'brand'], ['准备完成', '9', 'success'], ['待补资源', '3', 'warning']],
    feedTitle: '欢迎更新',
    feedAction: '查看新人',
    feedItems: [
      ['设备与账号已准备完成', 'IT 已为 9 位新人完成设备开通和系统账号配置。', 'IT 支持 · 今天 10:00', '已就绪', 'success'],
      ['两位新人导师待确认', '导师分配仍有缺口，需要业务负责人补齐安排。', 'HRBP · 今天 10:25', '待安排', 'warning'],
    ],
    taskTitle: '入职动作',
    taskAction: '导出清单',
    taskItems: [
      ['首周任务包待发送', '新人需要在到岗前收到首周学习和流程清单。', 'HR 运营 · 待发送', '待完成', 'brand'],
      ['欢迎会资料待补齐', '一位讲师临时调整，需要更新议程和附件。', '组织发展 · 待修改', '需补充', 'warning'],
    ],
    membersTitle: '协作角色',
    membersDescription: '保留导师、HR 和 IT 责任链。',
    memberItems: [['HRBP', '负责欢迎流', '在线', 'success'], ['IT 支持', '负责设备与账号', '同步中', 'brand'], ['直属经理', '负责导师与业务安排', '待确认', 'warning']],
    notes: ['入职页的主线应该是“新人能否顺利开始工作”。', '欢迎流和资源准备要一起看，不要拆开。'],
  }),
  'community-announcements': buildTeamsScenario({
    eyebrow: 'Community Announcements',
    title: '社区公告台',
    description: '验证社区公告、讨论回应和运营节奏在 Teams 风格下的页面组织。',
    emphasis: '公告与回应',
    badges: [['Teams line', 'brand', 'filled'], ['Community'], ['Announcements']],
    channelTitle: 'Community updates',
    channelDescription: '适合公告、问答和社群运营页面。',
    channelItems: [['公告', '置顶内容', true], ['问答', '成员回应'], ['活动', '近期安排'], ['精选', '高价值帖子']],
    heroTitle: '社区公告页要把“官方公告”和“成员回应”组织成一条清晰的节奏。',
    heroBody: '这种页更接近频道公告，不适合做成营销式社群首页。',
    heroSupport: '适合客户社区、合作伙伴社区和内部社群公告页。',
    stats: [['本周公告', '7', 'brand'], ['活跃回应', '94', 'success'], ['待管理员回复', '6', 'warning']],
    feedTitle: '公告更新',
    feedAction: '查看置顶',
    feedItems: [
      ['四月产品升级公告已发布', '需要继续观察评论区中关于菜单迁移的高频问题。', '社区运营 · 刚刚', '已发布', 'success'],
      ['活动报名帖进入二次传播', '合作伙伴开始转发活动帖，需要运营继续跟进重点评论。', '市场社区 · 1 小时前', '进行中', 'brand'],
    ],
    taskTitle: '运营动作',
    taskAction: '安排回应',
    taskItems: [
      ['FAQ 回复模板待补充', '本次升级相关问题需要统一回复口径。', '社区支持 · 待补', '待完成', 'warning'],
      ['合作伙伴评论需手动跟进', '两条高价值评论需要业务负责人介入回复。', '伙伴运营 · 待分派', '需升级', 'brand'],
    ],
    membersTitle: '运营角色',
    membersDescription: '右栏聚焦谁在维护社区节奏。',
    memberItems: [['社区运营', '负责公告节奏', '在线', 'success'], ['产品代表', '负责专业答复', '同步中', 'brand'], ['伙伴运营', '负责高价值关系', '待跟进', 'warning']],
    notes: ['社区页先交代公告和回应，不要退化成内容流混排。', '重要公告和管理员动作应该比普通评论更强。'],
  }),
  'shift-handoff': buildTeamsScenario({
    eyebrow: 'Shift Handoff',
    title: '交接班中心',
    description: '验证交接记录、值守任务和待升级事项在 Teams 协作布局中的节奏。',
    emphasis: '交接班和待办',
    badges: [['Teams line', 'brand', 'filled'], ['Shift'], ['Handoff']],
    channelTitle: 'Shift handoff',
    channelDescription: '适合值守团队的交接与升级工作面。',
    channelItems: [['当前班次', '待交接内容', true], ['升级事项', '需继续跟进'], ['历史交接', '回看记录'], ['规则', '值守规范']],
    heroTitle: '交接班页要把“谁接手、接什么、风险在哪”讲清楚。',
    heroBody: '如果交接页只是一长串文本记录，值守人员还是要自己判断风险和优先级。',
    heroSupport: '适合运维值守、客服轮班和安全响应交接页。',
    stats: [['待交接事项', '11', 'brand'], ['已闭环', '23', 'success'], ['升级风险', '2', 'warning']],
    feedTitle: '交接记录',
    feedAction: '查看上一班',
    feedItems: [
      ['夜班已标记两项持续观察', '身份服务和支付通道在恢复后仍需继续观察 30 分钟。', '夜班值守 · 06:50', '继续观察', 'warning'],
      ['告警去重规则已调整', '下个班次无需再处理重复短信告警，可把注意力放回核心服务。', '平台值守 · 06:40', '已处理', 'success'],
    ],
    taskTitle: '接班动作',
    taskAction: '生成交接单',
    taskItems: [
      ['通知新班次负责人', '接班人需要先确认升级事项和外部广播状态。', '值守系统 · 自动提醒', '待确认', 'brand'],
      ['补全交接说明', '两项告警记录缺少根因推测，需要补充后再归档。', '质量复核 · 待补', '待完成', 'warning'],
    ],
    membersTitle: '班次角色',
    membersDescription: '右栏只保留谁在值守、谁负责升级。',
    memberItems: [['当前班次', '负责接手后续动作', '在线', 'success'], ['上一班次', '负责补充背景', '待联系', 'warning'], ['升级 owner', '负责高风险事项', '同步中', 'brand']],
    notes: ['交接班页面首屏必须帮助新班次快速建立上下文。', '持续观察和升级事项应该比历史记录更强。'],
  }),
  'webinar-operations': buildTeamsScenario({
    eyebrow: 'Webinar Operations',
    title: '活动运营频道',
    description: '验证线上活动准备、素材协调和直播值守在 Teams 风格下的工作面。',
    emphasis: '活动准备与值守',
    badges: [['Teams line', 'brand', 'filled'], ['Webinar'], ['Operations']],
    channelTitle: 'Webinar launch',
    channelDescription: '适合活动、直播和会务值守类协作页面。',
    channelItems: [['准备中', '素材与嘉宾', true], ['直播中', '值守与广播'], ['回放', '复盘与剪辑'], ['报名', '转化跟进']],
    heroTitle: '活动页需要同时承接准备动作、直播值守和会后动作，而不只是给一张日程表。',
    heroBody: '用 Teams 风格的频道节奏承接活动推进，比普通项目页更适合多角色协同。',
    heroSupport: '适合线上直播、宣讲会和合作伙伴活动运营。',
    stats: [['待准备项', '13', 'brand'], ['嘉宾确认', '6/7', 'success'], ['直播风险', '2', 'warning']],
    feedTitle: '活动更新',
    feedAction: '查看素材',
    feedItems: [
      ['主视觉和议程页已同步', '设计团队已按最新嘉宾名单更新视觉和介绍页。', '活动设计 · 今天 11:10', '已就绪', 'success'],
      ['直播网络演练待补跑', '一位讲师改用外部网络，需要补一次连线测试。', '直播技术 · 待执行', '需关注', 'warning'],
    ],
    taskTitle: '值守动作',
    taskAction: '生成 runbook',
    taskItems: [
      ['会中广播模板待确认', '开场提醒、故障通知和回放引导需要统一文案。', '活动运营 · 待确认', '待完成', 'brand'],
      ['报名转化跟进需拆分', '活动结束后需把高意向名单转给销售和伙伴运营。', '市场运营 · 待规划', '需跟进', 'warning'],
    ],
    membersTitle: '活动角色',
    membersDescription: '把活动中的关键角色留在侧栏。',
    memberItems: [['活动 owner', '负责整体节奏', '在线', 'success'], ['直播技术', '负责连线与故障', '同步中', 'brand'], ['内容团队', '负责素材与回放', '待确认', 'warning']],
    notes: ['活动页要强调准备和会中值守，不只是活动介绍。', '会后转化动作也应在同一工作面被看见。'],
  }),
  'incident-swarm': buildTeamsScenario({
    eyebrow: 'Incident Swarm',
    title: '事件协同频道',
    description: '验证事件协同、跨团队评论和升级广播在 Teams 风格下的页面表达。',
    emphasis: '事件协同频道',
    badges: [['Teams line', 'brand', 'filled'], ['Incident'], ['Swarm']],
    channelTitle: 'War room',
    channelDescription: '偏强协同和跨团队处理节奏。',
    channelItems: [['当前故障', '共同响应', true], ['外部广播', '状态同步'], ['恢复观察', '后续确认'], ['复盘', '根因与动作']],
    heroTitle: '事件协同页和普通事件响应页不同，它更强调“多人同时协作”。',
    heroBody: '适合在同一页内同时看到更新流、责任人和对外广播状态，减少在多个频道之间切换。',
    heroSupport: '适合大型故障的 war room 协同频道。',
    stats: [['活跃响应者', '19', 'brand'], ['已完成动作', '27', 'success'], ['外部广播', '2', 'warning']],
    feedTitle: '协同更新',
    feedAction: '查看时间线',
    feedItems: [
      ['缓存层已开始逐区恢复', '平台团队已按区域逐步恢复读流量，观察错误率是否回落。', '平台团队 · 刚刚', '处理中', 'brand'],
      ['客户状态页已同步影响范围', '外部沟通已更新受影响模块和缓解措施。', '客户沟通 · 5 分钟前', '已广播', 'success'],
    ],
    taskTitle: '协同动作',
    taskAction: '导出战情',
    taskItems: [
      ['待指定复盘 owner', '在恢复结束前需要确定复盘组织者和会后节奏。', '值守负责人 · 待决定', '待确认', 'warning'],
      ['日志包待上传', '两支团队仍需把关键日志汇总到统一位置。', '分析组 · 待上传', '需跟进', 'brand'],
    ],
    membersTitle: '响应角色',
    membersDescription: '右侧栏保留谁在协同、谁对外广播。',
    memberItems: [['事件指挥', '负责统一节奏', '在线', 'success'], ['平台团队', '负责恢复执行', '同步中', 'brand'], ['客户沟通', '负责外部状态', '已发布', 'warning']],
    notes: ['事件协同页比普通响应页更强调跨团队流动。', '对外广播状态必须在同页可见。'],
  }),
  'partner-standup': buildTeamsScenario({
    eyebrow: 'Partner Standup',
    title: '伙伴站会台',
    description: '验证伙伴协作、行动项和共享问题清单在 Teams 风格下的日常工作面。',
    emphasis: '伙伴协作与站会',
    badges: [['Teams line', 'brand', 'filled'], ['Partner'], ['Standup']],
    channelTitle: 'Partner sync',
    channelDescription: '适合渠道、伙伴和联合项目日常站会页。',
    channelItems: [['今日阻塞', '优先讨论', true], ['联合动作', '待完成事项'], ['素材共享', '文档与链接'], ['回顾', '上次决议']],
    heroTitle: '伙伴站会页要帮助双方快速看见阻塞、责任人与下一步动作。',
    heroBody: '与其做成泛项目页，不如把站会、阻塞和共享素材收口成一张轻协作页面。',
    heroSupport: '适合伙伴项目、联合交付和渠道支持团队。',
    stats: [['开放阻塞', '7', 'brand'], ['联合任务', '15', 'success'], ['待伙伴确认', '4', 'warning']],
    feedTitle: '站会更新',
    feedAction: '查看上次纪要',
    feedItems: [
      ['伙伴侧接口联调完成首轮', '当前剩余问题集中在权限键映射和环境白名单上。', '联调 owner · 今天', '推进中', 'brand'],
      ['销售素材已同步最新版本', '渠道伙伴可以直接使用更新后的演示截图和说明文案。', '营销支持 · 45 分钟前', '已同步', 'success'],
    ],
    taskTitle: '联合动作',
    taskAction: '转成任务',
    taskItems: [
      ['白名单申请待总部确认', '伙伴测试环境仍需补开两个出口地址。', '环境管理 · 待确认', '待总部', 'warning'],
      ['角色说明需补英文版', '伙伴培训资料需要补一版英文界面说明。', 'Enablement · 待产出', '需跟进', 'brand'],
    ],
    membersTitle: '协作角色',
    membersDescription: '侧栏保留主要伙伴角色和总部接口人。',
    memberItems: [['总部 PM', '负责内部协调', '在线', 'success'], ['伙伴交付', '负责联调执行', '同步中', 'brand'], ['渠道支持', '负责素材与培训', '待确认', 'warning']],
    notes: ['伙伴页更适合短站会节奏，不适合重文档页面。', '阻塞和联合动作必须在首屏可见。'],
  }),
} as const;
