// AUTO-GENERATED by cmd/gen-permissions — DO NOT EDIT.
// Source of truth: backend/internal/api/apperr/codes.go
//
// Usage:
//   import { ErrorCodes } from '@/api/v5/error-codes'
//   if (error.code === ErrorCodes.InvalidCredentials) { ... }

export const ErrorCodes = {
  /** 参数错误（通用） */
  ParamInvalid: 1001,
  /** 参数缺失 */
  ParamMissing: 1002,
  /** 参数格式错误（JSON 解析失败、类型不匹配等） */
  ParamFormat: 1003,
  /** 无效的资源 ID */
  InvalidID: 1004,
  /** 未登录或 token 无效 */
  Unauthorized: 2001,
  /** token 已过期 */
  TokenExpired: 2002,
  /** 无权限 */
  Forbidden: 2003,
  /** 缺少 API Key */
  APIKeyMissing: 2004,
  /** token 格式错误 */
  TokenBadFormat: 2005,
  /** 邮箱或密码错误 */
  InvalidCredentials: 2006,
  /** 账号已被禁用 */
  UserInactive: 2007,
  /** 资源不存在（通用） */
  NotFound: 3001,
  /** 用户不存在 */
  UserNotFound: 3002,
  /** 协作空间不存在 */
  WorkspaceNotFound: 3003,
  /** 菜单不存在 */
  MenuNotFound: 3004,
  /** 角色不存在 */
  RoleNotFound: 3005,
  /** 暂无管理的协作空间 */
  NoManagedWorkspace: 3006,
  /** 角色编码已存在 */
  RoleCodeExists: 3007,
  /** 协作空间角色不存在或无权操作 */
  WorkspaceRoleNotFound: 3010,
  /** 系统菜单不可删除 */
  MenuSystemProtected: 3011,
  /** 无效的上级 */
  InvalidParent: 3012,
  /** 业务冲突（通用） */
  Conflict: 3013,
  /** 用户名已存在 */
  UserExists: 3014,
  /** 邮箱已存在 */
  EmailExists: 3015,
  /** 系统角色不可删除 */
  SystemRoleProtected: 3016,
  /** 商品不存在 */
  ProductNotFound: 3017,
  /** 全局角色权限不可在此修改 */
  GlobalRolePermReadOnly: 3018,
  /** 该用户已在协作空间中 */
  WorkspaceMemberExists: 3019,
  /** 成员不在协作空间中 */
  WorkspaceMemberNotFound: 3020,
  /** 暂无协作空间 */
  NoCurrentWorkspace: 3021,
  /** 内部错误（通用） */
  Internal: 5001,
  /** 数据库错误 */
  Database: 5002,
  /** 外部服务错误 */
  External: 5003,
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
