export const queryKeys = {
  auth: {
    currentUser: ['auth', 'currentUser'] as const,
  },
  dashboard: {
    summary: ['dashboard', 'summary'] as const,
  },
  inbox: {
    summary: ['inbox', 'summary'] as const,
    list: (filters: string) => ['inbox', 'list', filters] as const,
    detail: (deliveryId: string) => ['inbox', 'detail', deliveryId] as const,
  },
  navigation: {
    menuSpaces: ['navigation', 'menuSpaces'] as const,
    runtime: (spaceKey: string) => ['navigation', 'runtime', spaceKey] as const,
  },
  menu: {
    tree: (spaceKey: string, keyword = '') => ['menu', 'tree', spaceKey, keyword] as const,
    detail: (menuId: string, spaceKey: string) => ['menu', 'detail', menuId, spaceKey] as const,
    pages: (menuId: string, spaceKey: string) => ['menu', 'pages', menuId, spaceKey] as const,
    manageGroups: (spaceKey: string) => ['menu', 'manageGroups', spaceKey] as const,
    runtimePages: (spaceKey: string) => ['menu', 'runtimePages', spaceKey] as const,
  },
  page: {
    list: (filters: string, spaceKey: string) => ['page', 'list', spaceKey, filters] as const,
    detail: (pageId: string) => ['page', 'detail', pageId] as const,
    menuOptions: (spaceKey: string) => ['page', 'menuOptions', spaceKey] as const,
    unregistered: ['page', 'unregistered'] as const,
    breadcrumbPreview: (pageId: string) => ['page', 'breadcrumbPreview', pageId] as const,
    accessTrace: (filters: string) => ['page', 'accessTrace', filters] as const,
  },
  apiEndpoint: {
    list: (filters: string) => ['apiEndpoint', 'list', filters] as const,
    overview: ['apiEndpoint', 'overview'] as const,
    categories: ['apiEndpoint', 'categories'] as const,
    unregistered: (filters: string) => ['apiEndpoint', 'unregistered', filters] as const,
    scanConfig: ['apiEndpoint', 'scanConfig'] as const,
  },
  role: {
    list: (filters: string) => ['role', 'list', filters] as const,
    detail: (roleId: string) => ['role', 'detail', roleId] as const,
    packages: (roleId: string) => ['role', 'packages', roleId] as const,
    actions: (roleId: string) => ['role', 'actions', roleId] as const,
    menus: (roleId: string) => ['role', 'menus', roleId] as const,
  },
  user: {
    list: (filters: string) => ['user', 'list', filters] as const,
    detail: (userId: string) => ['user', 'detail', userId] as const,
    packages: (userId: string) => ['user', 'packages', userId] as const,
    menus: (userId: string) => ['user', 'menus', userId] as const,
    permissionDiagnosis: (userId: string) => ['user', 'permissionDiagnosis', userId] as const,
  },
  permission: {
    list: (filters: string) => ['permission', 'list', filters] as const,
    groups: ['permission', 'groups'] as const,
    detail: (actionId: string) => ['permission', 'detail', actionId] as const,
    endpoints: (actionId: string) => ['permission', 'endpoints', actionId] as const,
    consumers: (actionId: string) => ['permission', 'consumers', actionId] as const,
  },
  featurePackage: {
    list: (filters: string) => ['featurePackage', 'list', filters] as const,
    detail: (packageId: string) => ['featurePackage', 'detail', packageId] as const,
    children: (packageId: string) => ['featurePackage', 'children', packageId] as const,
    actions: (packageId: string) => ['featurePackage', 'actions', packageId] as const,
    menus: (packageId: string) => ['featurePackage', 'menus', packageId] as const,
    teams: (packageId: string) => ['featurePackage', 'teams', packageId] as const,
    relationTree: ['featurePackage', 'relationTree'] as const,
    impactPreview: (packageId: string) => ['featurePackage', 'impactPreview', packageId] as const,
  },
  system: {
    fastEnter: ['system', 'fastEnter'] as const,
    menuSpaceMode: ['system', 'menuSpaceMode'] as const,
    menuSpaces: ['system', 'menuSpaces'] as const,
    menuSpaceHostBindings: ['system', 'menuSpaceHostBindings'] as const,
  },
  message: {
    dispatchOptions: (scope: string) => ['message', 'dispatchOptions', scope] as const,
    templates: (filters: string, scope: string) => ['message', 'templates', scope, filters] as const,
    senders: (scope: string) => ['message', 'senders', scope] as const,
    recipientGroups: (scope: string) => ['message', 'recipientGroups', scope] as const,
    records: (filters: string, scope: string) => ['message', 'records', scope, filters] as const,
    recordDetail: (recordId: string, scope: string) => ['message', 'recordDetail', scope, recordId] as const,
  },
  team: {
    list: (filters: string) => ['team', 'list', filters] as const,
    detail: (teamId: string) => ['team', 'detail', teamId] as const,
    members: (teamId: string) => ['team', 'members', teamId] as const,
    myTeamMembers: ['team', 'myTeamMembers'] as const,
    myTeamBoundaryRoles: ['team', 'myTeamBoundaryRoles'] as const,
    myTeamActionOrigins: ['team', 'myTeamActionOrigins'] as const,
    myTeamMenuOrigins: ['team', 'myTeamMenuOrigins'] as const,
    myTeamBoundaryRoleActions: (roleId: string) => ['team', 'myTeamBoundaryRoleActions', roleId] as const,
    myTeamBoundaryRoleMenus: (roleId: string) => ['team', 'myTeamBoundaryRoleMenus', roleId] as const,
    myTeamBoundaryRolePackages: (roleId: string) => ['team', 'myTeamBoundaryRolePackages', roleId] as const,
  },
} as const
